-- Create tables for the e-commerce site

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10, 2) NOT NULL,
    stock NUMBER NOT NULL,
    image_url VARCHAR2(500),
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    order_date DATE DEFAULT sysdate NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (order_id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

-- Insert initial product data
INSERT INTO products (name, description, price, stock) VALUES ('Laptop', 'High-performance laptop', 999.99, 50);
INSERT INTO products (name, description, price, stock) VALUES ('Smartphone', 'Latest model smartphone', 499.99, 100);
INSERT INTO products (name, description, price, stock) VALUES ('Tablet', 'Portable and powerful tablet', 299.99, 80);
INSERT INTO products (name, description, price, stock, image_url) VALUES (
    'Tablet',
    'Portable and powerful tablet, perfect for browsing and multimedia.',
    299.99,
    80,
    'http://example.com/images/tablet.jpg'
);